name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:8-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 23.x
      uses: actions/setup-node@v4
      with:
        node-version: '23.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint with fix
      run: npm run lint:fix

    - name: Format with fix
      run: npm run format

    - name: Check for changes after lint/format
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Files were modified by linting/formatting:"
          git status --short
          git diff
          echo "::warning::Code formatting or linting made changes. Please commit these changes."
        else
          echo "No changes made by linting/formatting."
        fi

    - name: Build
      run: npm run build

    - name: Run unit tests
      run: npm run test:unit

    - name: Run integration tests
      run: npm run test:int
      env:
        REDIS_URL: redis://localhost:6379

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          coverage/
          junit.xml
        retention-days: 5

    - name: Test Summary
      uses: test-summary/action@v2
      if: always()
      with:
        paths: |
          junit.xml